#!/usr/bin/env bash
# script that will display information about subdomains.


display() {
   if [ -n "$2" ]
   then
      dig "$2.$1" | awk '/;; ANSWER SECTION:/ {getline; print "The subdomain '"$2"' is a " $4 " record and points to " $5}'
   else
      dig "www.$1" | awk '/;; ANSWER SECTION:/ {getline; print "The subdomain www is a " $4 " record and points to " $5}'
      dig "lb-01.$1" | awk '/;; ANSWER SECTION:/ {getline; print "The subdomain lb-01 is a " $4 " record and points to " $5}'
      dig "web-01.$1" | awk '/;; ANSWER SECTION:/ {getline; print "The subdomain web-01 is a " $4 " record and points to " $5}'
      dig "web-02.$1" | awk '/;; ANSWER SECTION:/ {getline; print "The subdomain web-02 is a " $4 " record and points to " $5}'
   fi
}


display "$1" "$2"