#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect below requirements

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 http:\/\/google.com;\n\t}/" /etc/nginx/sites-available/default
sudo service nginx restart
