#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.



sudo apt-get -y update
sudo apt-get -y install haproxy


echo "
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend lb-01
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 806605-web-01 34.224.6.206:80
    server 806605-web-02 34.201.161.84:80" > /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
