#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.



sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sh -c 'echo "
   defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect 5000
    timeout client  30000
    timeout server  30000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend lb-01
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 806605-web-01 34.224.6.206:80
    server 806605-web-02 34.201.161.84:80" > /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
