#!/usr/bin/env bash
# find out what’s Nginx installation from listening on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /run/nginx.pid
