#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process
echo $$ > /var/run/myscript.pid
i=1
while ((i == 1))
do
   trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
   trap "echo Y U no love me?!" SIGINT
   trap "rm /var/run/myscript.pid; exit" SIGQUIT
   echo "To infinity and beyond"
   sleep 2
done
